# Generated by Django 5.2.16 on 2026-07-18 00:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1024)),
                ('file_name', models.CharField(max_length=255)),
                ('source_url', models.CharField(blank=True, default='', max_length=2048)),
                ('youtube_title_original', models.CharField(blank=True, default='', max_length=255)),
                ('youtube_title_pt_br', models.TextField(blank=True, default='')),
                ('thumbnail_path', models.CharField(blank=True, default='', max_length=1024)),
                ('extension', models.CharField(blank=True, max_length=16)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('source_duration_seconds', models.FloatField(blank=True, null=True)),
                ('original_language', models.CharField(default='auto', max_length=24)),
                ('storage_location', models.CharField(choices=[('exec', 'exec'), ('library', 'library')], default='exec', max_length=16)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_mode', models.CharField(choices=[('pipeline', 'pipeline'), ('remux', 'remux')], default='pipeline', max_length=24)),
                ('status', models.CharField(choices=[('discovered', 'discovered'), ('queued', 'queued'), ('running', 'running'), ('stopping', 'stopping'), ('stopped', 'stopped'), ('success', 'success'), ('failed', 'failed'), ('skipped', 'skipped')], default='queued', max_length=24)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('log_file_path', models.CharField(blank=True, max_length=1024)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('process_group_id', models.IntegerField(blank=True, null=True)),
                ('stop_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pipeline_ui.videoasset')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_profile', to='pipeline_ui.videoasset')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(choices=[('download', 'download'), ('extract', 'extract'), ('transcribe', 'transcribe'), ('translate', 'translate'), ('audiobook', 'audiobook'), ('remux', 'remux')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=24)),
                ('detail', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipeline_ui.pipelinerun')),
            ],
            options={
                'unique_together': {('pipeline_run', 'step_name')},
            },
        ),
    ]
