# Generated by Django 5.2.15 on 2026-07-04 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1024, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=16)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('original_language', models.CharField(default='auto', max_length=24)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('discovered', 'discovered'), ('queued', 'queued'), ('running', 'running'), ('stopping', 'stopping'), ('stopped', 'stopped'), ('success', 'success'), ('failed', 'failed'), ('skipped', 'skipped')], default='queued', max_length=24)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('log_file_path', models.CharField(blank=True, max_length=1024)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('process_group_id', models.IntegerField(blank=True, null=True)),
                ('stop_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pipeline_ui.videoasset')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('google', 'google'), ('nllb_local', 'nllb_local'), ('deepl_doc', 'deepl_doc'), ('gemini', 'gemini')], default='google', max_length=32)),
                ('nllb_profile', models.CharField(choices=[('fast', 'fast'), ('legacy', 'legacy'), ('custom', 'custom')], default='fast', max_length=16)),
                ('nllb_max_input_length', models.PositiveIntegerField(default=768)),
                ('nllb_max_new_tokens', models.PositiveIntegerField(default=192)),
                ('nllb_gpu', models.BooleanField(default=True)),
                ('nllb_legacy', models.BooleanField(default=False)),
                ('deepl_endpoint', models.CharField(default='free', max_length=64)),
                ('reset_deepl_keys_state', models.BooleanField(default=False)),
                ('normalize_dry_run', models.BooleanField(default=False)),
                ('cuda_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_profile', to='pipeline_ui.videoasset')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(choices=[('extract', 'extract'), ('transcribe', 'transcribe'), ('translate', 'translate'), ('audiobook', 'audiobook')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=24)),
                ('detail', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipeline_ui.pipelinerun')),
            ],
            options={
                'unique_together': {('pipeline_run', 'step_name')},
            },
        ),
    ]
