# Generated by Django 5.2.16 on 2026-07-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_ui', '0011_download_phase_and_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoasset',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='youtube_title_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='youtube_title_pt_br',
            field=models.TextField(blank=True, default=''),
        ),
    ]
