# Generated by Django 5.2.16 on 2026-07-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline_ui", "0012_videoasset_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoasset",
            name="thumbnail_path",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
